---
- name: Perform setup tasks
  ansible.builtin.include_tasks: setup.yml

- name: Install docker-ce and containerd
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: "{{ docker_packages_state }}"
    cache_valid_time: 3600

- name: Adding ansible user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  register: user_added_to_docker_group

- name: Install docker-compose
  ansible.builtin.apt:
    pkg:
      - docker-compose-plugin
    state: "{{ docker_packages_state }}"
    cache_valid_time: 3600
  when: docker_install_compose | bool

- name: Reset ssh connection if required
  ansible.builtin.include_tasks: reset_connection.yml
  when: user_added_to_docker_group.changed
