---
- name: Install dependencies.
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    cache_valid_time: 3600

- name: Add GPG key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository.
  apt_repository:
    repo: "deb [arch={{ docker_arch[ansible_architecture] }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker-ce and containerd.
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    cache_valid_time: 3600

- name: Check docker is active.
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure docker group exists.
  become: no
  group:
    name: docker
    state: present
  register: _docker_group

- name: "Adding {{ ansible_user }} to docker group."
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- name: Reset ssh connection to force groups update for user.
  meta: reset_connection
